### ISSUE TITLE
header missing for win32

### ISSUE THREAD

**Issue by devulder** [livingcreative/kcanvas#14]
hi,
trying compile ion windows
on file canvastypes.h doesn't found header files
kcommon/c_util.h
kcommon/c_geometry.h

theirs files are not in the archive?
thanks,

**Comment by livingcreative** [comment]
Hello,

There's a build instruction in the wiki: https://github.com/livingcreative/kcanvas/wiki/Guide#build-instructions

The `kcanvas` project depends on headers from my other repo, named `kcommon`. Just clone it to the same dir you cloned `kcanvas` and it will work.

The final directory structure should look something like this   
```
\somedir
    \kcommon        <-- clonned kcommon repository
    \kcanvas            <-- clonned kcanvas repository
```

I know I should add this repo as a dependency, eventually I'll do something about automatic dependency resolution

**Comment by livingcreative** [comment]
Any luck?

**Comment by devulder** [comment]
hi
thanks for your reply, it's ok
sorry for the delay reply.

**Comment by livingcreative** [comment]
No worries, thanks for feedback. If you have any other issues I would be happy to help.
